import Head from 'next/head'
import { FaLink, FaSchool, FaUser } from 'react-icons/fa'
import { Chart, DataCard, EventMessageListItem, Status, Verify } from '@/components'
import { useEffect, useState } from 'react';



export default function Home() {
  const [wqi,setWQI] = useState(0)
  const [temp,setTemp] = useState(0)
  const [turbidity,setTurbidity] = useState(0)
  const [tds,setTDS] = useState(0)
  function getRandomValue(max:number,min:number) {
    // Generate a random decimal between 0 (inclusive) and 1 (exclusive)
    const randomDecimal = Math.random();

    // Scale and shift the random decimal to fit within the range of 2 to 5
    const minValue = min;
    const maxValue = max;
    const randomValue = minValue + randomDecimal * (maxValue - minValue);

    return Math.floor(randomValue);
  }
  useEffect(() => {
    console.log('TestOut')
      let timeint = setInterval(() => {
        console.log('Test')
        setWQI(getRandomValue(2,5))
        console.log(wqi)
      },10000)
      let timetds = setInterval(() => {
        console.log('Test')
        setTDS(getRandomValue(50,500))
        console.log(wqi)
      },8000)
      let timetemp = setInterval(() => {
        console.log('Test')
        setTemp(getRandomValue(15,28))
        console.log(wqi)
      },1000)
      let timeturb = setInterval(() => {
        console.log('Test')
        setTurbidity(getRandomValue(300,1000))
        console.log(wqi)
      },4000)

      return () => {
        clearInterval(timeint);
        clearInterval(timetemp);
        clearInterval(timetds);
        clearInterval(timeturb);
      }
  },[wqi])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-fit min-h-screen bg-blue-300 gradOne px-10 py-5 font-[raleway]">
        {/* Top Bar */}
        <div className="flex w-full h-fit min-h-[30vh] flex-wrap my-5">
          <div className="flex flex-col flex-1 mx-2 min-w-[250px] min-h-[30vh] h-fit p-5 bg-[rgba(255,255,255,0.5)] rounded-3xl drop-shadow-lg">
            <h1
              className="font-semibold tracking-wide mb-3"
              style={{ fontSize: "calc(0.7rem + 0.5vw)" }}
            >
              Location: Kaduna-NG
            </h1>

            <Status />
            <Verify/>
          </div>
          <div className="flex flex-col flex-1 mx-2 min-w-[250px] justify-center min-h-[30vh] h-fit bg-[rgba(255,255,255,0.5)] rounded-3xl drop-shadow-lg p-5">
            <div className="">
              <DataCard
                val={wqi}
                title='Water Quality Index'
                theme={3}
              />
              {/* <EventMessageListItem /> */}
            </div>
          </div>
          <div className="flex flex-col flex-1 mx-2 min-w-[250px] min-h-[30vh] h-fit bg-[rgba(255,255,255,0.5)] rounded-3xl drop-shadow-lg p-5">
            <h1 className="font-semibold tracking-wide mb-3">Institution</h1>
            <div className="flex w-full">
              <div
                className="flex-[0.4] aspect-square bg-cover bg-center bg-no-repeat"
                style={{ backgroundImage: "url('/img/afit_logo.png')" }}
              ></div>
              <div
                className="flex-1 flex flex-col justify-center"
                style={{ fontSize: "calc(0.6rem + 0.25vw)" }}
              >
                <div className="flex items-center">
                  <FaUser />
                  <p className="mx-2">Adetola Oluwatise - AFIT/EEE/18/0003</p>
                </div>

                <div className="flex items-center my-2">
                  <FaUser />
                  <p className="mx-2">Prof. Nurudeen (Supervisor)</p>
                </div>

                <div className="flex items-center my-2">
                  <FaSchool />
                  <p className="mx-2">
                    Airforce Institute of Technology <br /> Electrical Electronics Engineering Dept.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Stats */}
        <div className="w-full py-3 px-5 h-fit min-h-[55vh] bg-[rgba(255,255,255,0.5)] rounded-3xl drop-shadow-xl">
            <h1 className=' uppercase font-semibold tracking-wider' style={{fontSize:'calc(0.6rem + 0.5vw)'}}>
              Statistics
            </h1>
            <div className="flex flex-wrap w-full h-[60vh]">
                <div className="flex-1 min-w-[300px] mr-2">
                  <Chart/>
                </div>
                <div className="flex-[0.5] min-w-[300px]">
                    <DataCard
                      theme={0}
                      title='Temperature'
                      val={temp}
                    />
                    <DataCard
                      theme={1}
                      title='Turbidity'
                      val={turbidity}
                    />
                    <DataCard
                      theme={2}
                      title='Total Dissolved Solids'
                      val={tds}
                    />
                </div>
            </div>
        </div>
      </div>
    </>
  );
}
